[package]
name = "wavectl"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "wavectl stub (RC1g) — simulate-swaps, wt-equiv bins"

[[bin]]
name = "wavectl"
path = "src/bin/wavectl.rs"

[[bin]]
name = "wt-equiv"
path = "src/bin/wt-equiv.rs"
