[package]
name = "wavectl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
wmlb = { path = "../wmlb" }
waveform = { path = "../waveform" }
waveforge = { path = "../waveforge" }
waverunner = { path = "../waverunner" }
wavereport = { path = "../wavereport" }
env_logger = { workspace = true }
log = { workspace = true }
time = { workspace = true }
