[package]
name = "waveforge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
wmlb = { path = "../wmlb" }
wavelint = { path = "../wavelint" }
