[package]
name = "wmlb"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
time = { workspace = true }
log = { workspace = true }
