name: WaveML Acceptance
on:
  push: { branches: ["master"] }
  pull_request: { branches: ["master"] }
jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --workspace --all-targets
      - run: cargo test --workspace
      - run: |
          cargo run -p wavectl -- acceptance \
            --plan acceptance/tests.yaml \
            --outdir build/acceptance \
            --strict
          cat build/acceptance/index.md
      - uses: actions/upload-artifact@v4
        with:
          name: acceptance-artifacts
          path: |
            build/acceptance/**
            build/reports/**
            **/*.wfr.json
          if-no-files-found: warn
