name: WaveML CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Build & Gates
        run: |
          chmod +x scripts/ci/run_all_gates.sh
          scripts/ci/run_all_gates.sh
